### ISSUE TITLE
Ruby error on starting beef in the container

### ISSUE THREAD

**Issue by Arno0x** [phocean/dockerfile-beef#3]
Hi,

Just loaded the latest docker image from docker hub today. Then, running the container and starting Beef, I get the following error:

`root@kali:~# docker run --rm -it --net=host -v /home/phocean/.msf4:/root/.msf4:Z -v /tmp/msf:/tmp/data:Z --name=beef phocean/beef
 * Starting PostgreSQL 10 database server                                                  [ OK ] 
root@kali:/opt# cd beef/
root@kali:/opt/beef# ./beef 
Traceback (most recent call last):
	10: from ./beef:44:in `<main>'
	 9: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /opt/beef/core/loader.rb:16:in `<top (required)>'
	 6: from /usr/lib/ruby/vendor_ruby/bundler.rb:114:in `require'
	 5: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:65:in `require'
	 4: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:65:in `each'
	 3: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:76:in `block in require'
	 2: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:76:in `each'
	 1: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:80:in `block (2 levels) in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'uglifier'. (Bundler::GemRequireError)
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
Backtrace for gem load error is:
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/var/lib/gems/2.5.0/gems/uglifier-4.1.20/lib/uglifier.rb:5:in `require'
/var/lib/gems/2.5.0/gems/uglifier-4.1.20/lib/uglifier.rb:5:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:81:in `require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:76:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:76:in `block in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:65:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:65:in `require'
/usr/lib/ruby/vendor_ruby/bundler.rb:114:in `require'
/opt/beef/core/loader.rb:16:in `<top (required)>'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
./beef:44:in `<main>'
Bundler Error Backtrace:
`

Any idea of what the problem could be ?
Thanks

**Comment by phocean** [comment]
Hi,

Thank you for the report and sorry for the delay.

I just made important updates to the dependencies to match with the latest version of BeEF.

I also updated the instructions, make sure to read them (notably, the volume you mounted would not work as it includes my own local path).
